config/routes.rb
DvSimpex::Application.routes.draw do
  get "page/index"
  
  resources :itps

  resources :clients

  root :to=>'pages#index'
  

end

app/models/client.rb
class Client < ActiveRecord::Base
    has_many :itps, :dependent => :destroy
    accepts_nested_attributes_for :itps, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/models/itp.rb
class Itp < ActiveRecord::Base
  belongs_to :client
  scope :upcoming, lambda { where("data_expirarii >= ?", Time.zone.now).order("data_expirarii") }
  
  def self.search(search)
    if search
      find(:all, :conditions => ['nr_auto LIKE ?', "%#{search}%"])
    else
      find(:all, :order => "updated_at")
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.order("updated_at")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new
    @client.itps.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])
    @client.itps.build(params[:client][:itps_attributes]["0"])

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/itps_controller.rb
class ItpsController < ApplicationController
  # GET /itps
  # GET /itps.json
  def index    
    @itps = Itp.search(params[:search])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @itps }
    end
  end

  # GET /itps/1
  # GET /itps/1.json
  def show
    @itp = Itp.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @itp }
    end
  end

  # GET /itps/new
  # GET /itps/new.json
  def new
    @itp = Itp.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @itp }
    end
  end

  # GET /itps/1/edit
  def edit
    @itp = Itp.find(params[:id])
  end

  # POST /itps
  # POST /itps.json
  def create
    @itp = Itp.new(params[:itp])

    respond_to do |format|
      if @itp.save
        format.html { redirect_to @itp, notice: 'Itp was successfully created.' }
        format.json { render json: @itp, status: :created, location: @itp }
      else
        format.html { render action: "new" }
        format.json { render json: @itp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /itps/1
  # PUT /itps/1.json
  def update
    @itp = Itp.find(params[:id])

    respond_to do |format|
      if @itp.update_attributes(params[:itp])
        format.html { redirect_to @itp, notice: 'Itp was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @itp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /itps/1
  # DELETE /itps/1.json
  def destroy
    @itp = Itp.find(params[:id])
    @itp.destroy

    respond_to do |format|
      format.html { redirect_to itps_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @itps = Itp.upcoming
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/it_ps_helper.rb
module ItPsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nume %><br />
    <%= f.text_field :nume %>
  </div>
  <div class="field">
    <%= f.label :prenume %><br />
    <%= f.text_field :prenume %>
  </div>
  <div class="field">
    <%= f.label :telefon %><br />
    <%= f.text_field :telefon %>
  </div>
  <div class="field">
    <%= f.label :mail %><br />
    <%= f.text_field :mail %>
  </div>

  <%= f.fields_for :itps do |builder| %>
    <%= render "itp_form", :f => builder %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/_itp_form.html.erb
  <div class="field">
    <%= f.label :nr_auto %><br />
    <%= f.text_field :nr_auto %>
  </div>
  <div class="field">
    <%= f.label :data_expirarii %><br />
    <%= f.datetime_select :data_expirarii %>
  </div>
  <div class="field">
    <%= f.label :programare %><br />
    <%= f.datetime_select :programare %>
  </div>
  <div class="field">
    <%= f.label :observatii %><br />
    <%= f.text_area :observatii %>
  </div>

app/views/clients/edit.html.erb
<h1>Editare intrare</h1>

<%= render 'form' %>

<%= link_to 'Vizualizati', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <tr>
    <th>Nume</th>
    <th>Prenume</th>
    <th>Telefon</th>
    <th>Mail</th>
    <th>Creat</th>
    <th>Modificat</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <td><%= client.nume %></td>
    <td><%= client.prenume %></td>
    <td><%= client.telefon %></td>
    <td><%= client.mail %></td>
    <td><%= client.created_at.strftime('%d %b %Y') %></td>
    <td><%= client.updated_at.strftime('%d %b %Y') %></td>
    <td><%= link_to 'Vizualizeaza', client %></td>
    <td><%= link_to 'Modifica', edit_client_path(client) %></td>
    <td><%= link_to 'Sterge', client, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>Client nou</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nume:</b>
  <%= @client.nume %>
</p>

<p>
  <b>Prenume:</b>
  <%= @client.prenume %>
</p>

<p>
  <b>Telefon:</b>
  <%= @client.telefon %>
</p>

<p>
  <b>Mail:</b>
  <%= @client.mail %>
</p>

<p>
  <b>Creat:</b>
  <%= @client.created_at.strftime('%d %b %Y') %>
</p>

<p>
  <b>Modificat:</b>
  <%= @client.updated_at.strftime('%d %b %Y') %>
</p>


<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/itps/_form.html.erb
<%= form_for(@itp) do |f| %>
  <% if @itp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@itp.errors.count, "error") %> prohibited this itp from being saved:</h2>

      <ul>
      <% @itp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nr_auto %><br />
    <%= f.text_field :nr_auto %>
  </div>
  <div class="field">
    <%= f.label :data_expirarii %><br />
    <%= f.datetime_select :data_expirarii %>
  </div>
  <div class="field">
    <%= f.label :programare %><br />
    <%= f.datetime_select :programare %>
  </div>
  <div class="field">
    <%= f.label :observatii %><br />
    <%= f.text_area :observatii %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/itps/edit.html.erb
<h1>Modificare intrare</h1>

<%= render 'form' %>

<%= link_to 'Vizualizati', @itp %> |
<%= link_to 'Back', itps_path %>

app/views/itps/index.html.erb
<h1>ITP-uri</h1>

<table>
  <tr>
    <th>Nr auto</th>
    <th>Data expirarii</th>
    <th>Programare</th>
    <th>Observatii</th>
    <th>Telefon</th>
    <th>Mail</th>
    <th>Creat</th>
    <th>Modificat</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @itps.each do |itp| %>
  <tr>
    <td><%= itp.nr_auto %></td>
    <td><%= itp.data_expirarii.strftime('%d %b %Y') %></td>
    <td><%= itp.programare.strftime('%d %b %Y') %></td>
    <td><%= itp.observatii %></td>
    <td><%= itp.client.telefon %></td>
    <td><%= itp.client.mail %></td>
    <td><%= itp.created_at.strftime('%d %b %Y') %></td>
    <td><%= itp.updated_at.strftime('%d %b %Y') %></td>
    <td><%= link_to 'Modificati date client', edit_client_path(itp.client) %></td>
    <td><%= link_to 'Modificati date masina', edit_itp_path(itp) %></td>
    <td><%= link_to 'Stergeti', itp, confirm: 'Sunteti sigur?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Adaugati', new_itp_path %>

app/views/itps/new.html.erb
<h1>Intrare noua</h1>

<%= render 'form' %>

<%= link_to 'Back', itps_path %>

app/views/itps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nr auto:</b>
  <%= @itp.nr_auto %>
</p>

<p>
  <b>Data expirarii:</b>
  <%= @itp.data_expirarii.strftime('%d %b %Y') %>
</p>

<p>
  <b>Programare:</b>
  <%= @itp.programare.strftime('%d %b %Y') %>
</p>

<p>
  <b>Observatii:</b>
  <%= @itp.observatii %>
</p>

<p>
  <b>Client:</b>
  <%= @itp.client_id %>
</p>

<p>
  <b>Creat:</b>
  <%= @itp.created_at.strftime('%d %b %Y') %>
</p>

<p>
  <b>Modificat:</b>
  <%= @itp.updated_at.strftime('%d %b %Y') %>
</p>



<%= link_to 'Edit', edit_itp_path(@itp) %> |
<%= link_to 'Back', itps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DvSimpex</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<h1>DV-Simpex</h1>

<%= link_to 'Vizualizati intrarile din baza de date', itps_path %> <br />

<br />

<%= form_tag itps_path, :method => 'get' do %>
  Nr auto:
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Cautati", :name => nil %>
<% end %>

<br />

<%= link_to 'Adaugati un client nou', new_client_path %> 

<br /> <br />

<table>
  <tr>
    <th>Nr auto</th>
    <th>Data expirarii</th>
    <th>Programare</th>
    <th>Nume</th>
    <th>Prenume</th>
    <th>Telefon</th>
    <th>Mail</th>
    <th>Observatii</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @itps.each do |itp| %>
  <tr>
    <td><%= itp.nr_auto %></td>
    <td><%= itp.data_expirarii.strftime('%d %b %Y') %></td>
    <td><%= itp.programare.strftime('%d %b %Y') %></td>
    <td><%= itp.client.nume %></td>
    <td><%= itp.client.prenume %></td>
    <td><%= itp.client.telefon %></td>
    <td><%= itp.client.mail %></td>
    <td><%= itp.observatii %></td>
    <td><%= link_to 'Modificati date client', edit_client_path(itp.client) %></td>
    <td><%= link_to 'Modificati date masina', edit_itp_path(itp) %></td>
    <td><%= link_to 'Stergeti', itp, confirm: 'Suneti sigur?', method: :delete %></td>
  </tr>
<% end %>
</table>